[package]
name = "opentelemetry-application-insights"
version = "0.1.0"
authors = ["Jan Kuehle <jkuehle90@gmail.com>"]
edition = "2018"
description = "OpenTelemetry exporter for Azure Application Insights"
repository = "https://github.com/frigus02/opentelemetry-application-insights"
keywords = ["opentelemetry", "application insights", "tracing", "metrics"]
license = "MIT"
readme = "README.md"

[dependencies]
