[package]
name = "opentelemetry-application-insights"
version = "0.4.0"
authors = ["Jan Kuehle <jkuehle90@gmail.com>"]
edition = "2018"
description = "OpenTelemetry exporter for Azure Application Insights"
readme = "README.md"
repository = "https://github.com/frigus02/opentelemetry-application-insights"
license = "MIT"
keywords = ["opentelemetry", "tracing"]
categories = [
    "development-tools::debugging",
    "development-tools::profiling",
    "asynchronous",
]
exclude = [
    ".github/*",
    "README.tpl",
]

[dependencies]
async-trait = "0.1"
chrono = "0.4"
log = "0.4"
opentelemetry = "0.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ureq = { version = "1.3", features = ["json"] }

[dev-dependencies]
backtrace = "0.3.50"
env_logger = "0.7.1"
test-case = "1.0.0"
tokio = { version = "0.3.0", features = ["macros", "process", "rt-multi-thread", "time"] }
tracing = "0.1.19"
tracing-attributes = "0.1.10"
tracing-futures = "0.2.4"
tracing-opentelemetry = "0.8.0"
tracing-subscriber = "0.2.11"
version-sync = "0.9.1"

[badges]
github = { repository = "frigus02/opentelemetry-application-insights", workflow = "CI" }
