[package]
name = "opentelemetry-application-insights"
version = "0.10.0"
authors = ["Jan Kuehle <jkuehle90@gmail.com>"]
edition = "2018"
description = "OpenTelemetry exporter for Azure Application Insights"
readme = "README.md"
repository = "https://github.com/frigus02/opentelemetry-application-insights"
license = "MIT"
keywords = ["opentelemetry", "tracing"]
categories = [
    "development-tools::debugging",
    "development-tools::profiling",
    "asynchronous",
]
exclude = [
    ".github/*",
    "README.tpl",
]

[features]
reqwest-blocking-client = ["reqwest", "reqwest/blocking"]
reqwest-client = ["reqwest", "opentelemetry/tokio"]
surf-client = ["surf"]

[dependencies]
async-trait = "0.1"
bytes = "0.5"
chrono = "0.4"
http = "0.2"
thiserror = "1"
opentelemetry = "0.11"
opentelemetry-semantic-conventions = "0.3"
reqwest = { version = "0.10", optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
surf = { version = "2.0", optional = true }
once_cell = "1"

[dev-dependencies]
async-std = { version = "1.6.5", features = ["attributes"] }
backtrace = "0.3.50"
env_logger = "0.8.1"
opentelemetry-application-insights = { path = ".", features = ["reqwest-blocking-client"] }
test-case = "1.0.0"
tokio = { version = "0.2.22", features = ["macros", "process", "time"] }
version-sync = "0.9.1"

[package.metadata.docs.rs]
all-features = true

[badges]
github = { repository = "frigus02/opentelemetry-application-insights", workflow = "CI" }

[[example]]
name = "http_client_reqwest"
required-features = ["reqwest-client"]

[[example]]
name = "http_client_surf"
required-features = ["surf-client", "opentelemetry/async-std"]

[[example]]
name = "opentelemetry"
required-features = ["reqwest-client"]
