[package]
name = "opentelemetry-application-insights"
version = "0.1.0"
authors = ["Jan Kuehle <jkuehle90@gmail.com>"]
edition = "2018"
description = "OpenTelemetry exporter for Azure Application Insights"
repository = "https://github.com/frigus02/opentelemetry-application-insights"
keywords = ["opentelemetry", "application insights", "tracing", "metrics"]
license = "MIT"
readme = "README.md"

[dependencies]
base64 = "0.12.2"
chrono = "0.4.11"
opentelemetry = "0.6.0"
reqwest = { version = "0.10.6", features = ["blocking", "json"] }
serde = { version = "1.0.113", features = ["derive"] }

[dev-dependencies]
tokio = { version = "0.2", features = ["macros", "process"] }
opentelemetry-jaeger = "0.5.0"
