[package]
name = "opentelemetry-application-insights"
version = "0.16.0"
authors = ["Jan Kuehle <jkuehle90@gmail.com>"]
edition = "2018"
description = "OpenTelemetry exporter for Azure Application Insights"
readme = "README.md"
repository = "https://github.com/frigus02/opentelemetry-application-insights"
license = "MIT"
keywords = ["opentelemetry", "tracing"]
categories = [
    "development-tools::debugging",
    "development-tools::profiling",
    "asynchronous",
]
exclude = [
    ".github/*",
    "README.tpl",
]

[features]
reqwest-blocking-client = ["reqwest-client"]
reqwest-blocking-client-rustls = ["reqwest-client-rustls"]
reqwest-client = ["opentelemetry-http/reqwest", "reqwest/native-tls"]
reqwest-client-rustls = ["opentelemetry-http/reqwest", "reqwest/rustls-tls"]
surf-client = ["opentelemetry-http/surf"]

[dependencies]
async-trait = "0.1"
chrono = "0.4"
http = "0.2"
once_cell = "1"
opentelemetry = "0.15"
opentelemetry-http = "0.4"
opentelemetry-semantic-conventions = "0.7"
reqwest = { version = "0.11", default-features = false, features = ["blocking"], optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"

[dev-dependencies]
async-std = { version = "1.9.0", features = ["attributes"] }
backtrace = "0.3.60"
env_logger = "0.8.4"
opentelemetry = { version = "0.15.0", features = ["rt-tokio"] }
opentelemetry-application-insights = { path = ".", features = ["reqwest-client", "reqwest-blocking-client"] }
surf = "2.2.0"
test-case = "1.1.0"
tokio = { version = "1.7.0", features = ["rt", "macros", "process", "time"] }
version-sync = "0.9.2"

[package.metadata.docs.rs]
all-features = true

[badges]
github = { repository = "frigus02/opentelemetry-application-insights", workflow = "CI" }

[[example]]
name = "attributes"
required-features = ["reqwest-client"]

[[example]]
name = "http_client_reqwest"
required-features = ["reqwest-client", "opentelemetry/rt-tokio"]

[[example]]
name = "http_client_reqwest_blocking"
required-features = ["reqwest-client"]

[[example]]
name = "http_client_surf"
required-features = ["surf-client", "opentelemetry/rt-async-std"]

[[example]]
name = "opentelemetry"
required-features = ["reqwest-client", "opentelemetry/rt-tokio"]
