on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: CI

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run cargo build (trace only)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --no-default-features --features trace
      - name: Run cargo build (logs only)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --no-default-features --features logs
      - name: Run cargo build (metrics only)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --no-default-features --features metrics
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features
      - name: Build tracing example
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path examples/tracing/Cargo.toml
